---
- hosts: 127.0.0.1
  tasks:
    - name: update the system
      yum:
        name: "*"
        state: latest

    - name: restart system to reboot to newest kernel
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: wait for 10 seconds
      pause:
      seconds: 10

    - name: wait for the system to reboot
      wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60